### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by gulyx** [elastest/elastest-torm#1]
@franciscoRdiaz @micaelgallego @EduJGURJC cannot build the project `elastest/elastest-torm/elastest-torm/`
.
Is that "normal"?
Why I should need a private key in order to build?

Any suggestion?

> [INFO] 
> [INFO] --- maven-failsafe-plugin:2.18.1:integration-test (default) @ elastest-torm ---
> [INFO] 
> [INFO] --- maven-failsafe-plugin:2.18.1:verify (default) @ elastest-torm ---
> [INFO] Failsafe report directory: ... ...
> [INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ elastest-torm ---
> gpg: no default secret key: Nessuna chiave segreta
> gpg: signing failed: Nessuna chiave segreta
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------

**Comment by franciscoRdiaz** [comment]
Hi,

No, that  is not normal.
The project must build correctly using maven command "mvn clean package".

Try it and tell us.

**Comment by gulyx** [comment]
@franciscoRdiaz launching `mvn clean package` the project builds.

However, launching `mvn clean install` does not work. Can you explain why?

**Comment by franciscoRdiaz** [comment]
@gulyx If you run `mvn clean install`, then maven-gpg-plugin` plugin is executed and you need to configure the passphrase in the settings.xml file. We do not do it in local, because any artifact is not going to be deployed from local. This configuration (settings.xml with a passphrase) is attached in Jenkins Job.

Solutions:
- To work with elastest-torm is not necesary to do `mvn clean install` in local.
- Comment the plugin configuration of the `maven-gpg-plugin` into the pom.xml

I do not know if you need any further clarification.

**Comment by gulyx** [comment]
@franciscoRdiaz thanks for the clarification. With PR #2 I reported part of this info into the README.md file.

In addition, once I build the project with `mvn clean package`, how can I run it?
It seems that running it as a plain java application from jar won't work on http://localhost:8080.
Am I misunderstanding something?

**Comment by gulyx** [comment]
@franciscoRdiaz thanks for your updates with your last commits. I guess I succeeded in both set up the environment and build the project ... nevertheless I am still not able to launch it. Also I have some minor comment to report.

Maybe the easiest way to interact is by voice. Can we setup a with a quick call?

@micaelgallego

**Comment by franciscoRdiaz** [comment]
Hi @gulyx!  Tell me what is the problem did you encounter whereas configuring the development environment.

**Comment by franciscoRdiaz** [comment]
@gulyx I do not know if it will affect you, but i have found an error in the development documentation. The docker-compose command was wrong. It's already fixed.

`docker-compose -f docker-compose-dev.yml up -d`

**Comment by gulyx** [comment]
@franciscoRdiaz not really a prob, just some aspect I would you to discuss/clarify by voice.

**Comment by gulyx** [comment]
@franciscoRdiaz thanks for the call everting looks ok now. in the next days i will propose some update in the doc.

**Comment by franciscoRdiaz** [comment]
Your welcome @gulyx ! Thanks to you. All the help received is good.
